### ISSUE TITLE
桌面版ZYplayer导出的源不能使用

### ISSUE THREAD

**Issue by jinyulei** [waifu-project/movie#15]
桌面版ZYplayer导出的源不能使用，已上传到网站上切确认网站可以链接。json格式
https://gcore.jsdelivr.net/gh/jinyulei/assets@master/movie.json
是否格式有误？（ZYPlayer直接导出来的）

**Comment by d1y** [comment]
@jinyulei , 请问不能使用指的是?

1. 网络导入的为空(在 #13 已解决, 但还还未发行版本 🤔)

**Comment by jinyulei** [comment]
> 
是的，谢谢回复。
