### ISSUE TITLE
播放界面功能增强

### ISSUE THREAD

**Issue by meinvtuzai** [waifu-project/movie#18]
播放界面要实现右边上下滑动音量调节，左边亮度调节才行，要不不爽。再就是播放时直接全屏吧，要不看着很别扭。

**Comment by meinvtuzai** [comment]
再就是播放列表界面增加影片衔接地址，方便直接调用工具下载就完美了。

**Comment by d1y** [comment]
> 播放界面要实现右边上下滑动音量调节，左边亮度调节

这里暂未实现。。

**Comment by d1y** [comment]
> 播放界面要实现右边上下滑动音量调节，左边亮度调节

这里暂未实现。。
