### ISSUE TITLE
[功能请求] 种子视频源

### ISSUE THREAD

**Issue by Pantyhose-X** [waifu-project/movie#2]
在线播放种子不要下载。
从海盗湾 等获取Torrent视频源 https://www.mizpee.com/best-torrent-sites/  获取标题 ，torrent链接，截图，

可以参考这个种子在线播放库 https://github.com/webtorrent

**Comment by d1y** [comment]
//TODO

做是可以做，不过种子一般都是需要科学上网才能下载播放的。

另外，我希望yy只是个纯粹的播放器🤔

**Comment by Pantyhose-X** [comment]
用户自己科学上网缓存一下视频源。 里的`标题 截图 torrent链接`
现在种子不是支持，不下载在线播放了吗？
要下载才能播放那我还不如用[LibreTorrent](https://github.com/proninyaroslav/libretorrent)安装下载器。
