### ISSUE TITLE
受不了这播放页面🙉🙉🙉

### ISSUE THREAD

**Issue by gxylfm** [waifu-project/movie#20]
![Screenshot_20220813_163316_io github d1y movie movie](https://user-images.githubusercontent.com/57065133/184476015-87879120-8cbf-43f5-8221-fcb0ce328902.jpg)
![Screenshot_20220813_163258_io github d1y movie movie](https://user-images.githubusercontent.com/57065133/184476020-0f62fe76-e489-407b-876e-7a4772bbbd6a.jpg)
![Screenshot_20220813_163305_io github d1y movie movie](https://user-images.githubusercontent.com/57065133/184476025-ea2e1223-26be-41f8-9a0c-dc6bdff659ca.jpg)
![Screenshot_20220813_163241_io github d1y movie movie](https://user-images.githubusercontent.com/57065133/184476026-ca337435-3f2a-4da0-b158-ca917e0d35a6.jpg)

**Comment by d1y** [comment]
#18 正在修复完善, 打开播放若加载成功则自动全屏, 若失败则不全屏会给一个退出按钮

![fix_fullscreen](https://user-images.githubusercontent.com/45585937/184525749-c9a061fa-bbf4-43fd-9d92-a4a9a05c7c19.gif)

**Comment by meinvtuzai** [comment]
哈哈，一打开就全屏吧，太难受了，确实不行！

**Comment by d1y** [comment]
> 哈哈，一打开就全屏吧，太难受了，确实不行！

综合考量过, 还是给个缓冲带时间吧, 若加载成功就全屏, 不成功则不全屏🧐

**Comment by d1y** [comment]
#22 已修复, 现在播放视频就可以全屏
