### ISSUE TITLE
提交一个小小新建议

### ISSUE THREAD

**Issue by 977288629** [waifu-project/movie#26]
希望前端可以单独设置单个视频源，通过josn导入视频源找josn文件有点麻烦

**Comment by d1y** [comment]
我考虑了一下, 还是有点不想在yoyo上实现(实际上我确实用web实现过一个, 但是意义不大, 参考: https://github.com/waifu-project/assets)

主要是规则还没定好, 暂时自己找源就直接用 zyplayer 规则的吧, 要不就是参考: https://github.com/waifu-project/movie/dev/docs/源制作.md 自己制作一个 `json` 文件走导入逻辑

**Comment by d1y** [comment]
这个 issues 我暂时关了哈
