### ISSUE TITLE
v2.1.0+7 W11 下双击没反应

### ISSUE THREAD

**Issue by Vanp11** [waifu-project/movie#37]
v2.1.0+7 W11 下双击没反应；v2.1.0+5 W11 能打开，但windows defender报有毒

**Comment by d1y** [comment]
有没有更多的上下文信息, 报毒猜测可能是 `libisar` 🤔
打不开的话, 可以直接在终端启动一个二进制看一下什么报错信息

**Comment by Vanp11** [comment]
> 有没有更多的上下文信息, 报毒猜测可能是 `libisar` 🤔 打不开的话, 可以直接在终端启动一个二进制看一下什么报错信息
### ### 


> 谢谢，计算机水平有限，您说的我不会。现在弄了几下，发现任务栏中显示程序正在运行，但却没有程序的窗口显示
