### ISSUE TITLE
Mac OS build iOS 15 pro error 

### ISSUE THREAD

**Issue by jok886** [waifu-project/movie#47]
Launching lib/main.dart on iPhone 15 Pro in debug mode...
Running Xcode build...
Xcode build done.                                            8.8s
Failed to build iOS app
Error (Xcode): lib/isar/schema/history_schema.dart:3:6: Error: Error when reading 'lib/isar/schema/history_schema.g.dart': No such file or directory

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro.

part 'history_schema.g.dart';  这个报错   是不是关联库不对 ？

**Comment by jok886** [comment]
cd 你的工程目录

flutter packages pub run build_runner build //使用 build_runner 生成 .g.dart 文件   参考解决链接  https://www.jianshu.com/p/e52c4d2a8df8

**Comment by d1y** [comment]
参考这里: https://github.com/waifu-project/movie/blob/dev/docs/start_dev.md
