### ISSUE TITLE
不能导入txt文本源

### ISSUE THREAD

**Issue by jinyulei** [waifu-project/movie#5]
首先感谢开发的安卓版本，然后提一些使用中发现的问题：
不能直接导入txt文本源，网络地址不能导入https://netcut.cn/类网络剪切板

**Comment by d1y** [comment]
还没支持文本导入方式
（真的有的这个需求吗）

**Comment by jinyulei** [comment]
有些测试源或是特殊源，本地导入更合适吧，

**Comment by d1y** [comment]
todo，有时间就做哈，方便留个联系方式吗

**Comment by d1y** [comment]
https://github.com/waifu-project/movie/pull/8
