### ISSUE TITLE
官方源获取的内容为空有解决办法吗

### ISSUE THREAD

**Issue by AlterGu** [waifu-project/movie#6]

**Comment by d1y** [comment]
> 

貌似 `cdn.jsdelivr.net` 被墙了

```dart
const kBarHeightWidget = SizedBox(
  height: kBarHeight,
);
const FetchMirrorAPI = "https://cdn.jsdelivr.net/gh/waifu-project/assets@latest/s.json";
```

![image](https://user-images.githubusercontent.com/45585937/158007182-1ede5736-9f91-40dd-9a2d-a4f75ee6cfaf.png)

**Comment by d1y** [comment]
不知道咋俩说的是不是同一个频道嗷

**Comment by d1y** [comment]
已处理: https://github.com/waifu-project/movie/pull/13
