### ISSUE TITLE
获取的内容为空

### ISSUE THREAD

**Issue by AlterGu** [waifu-project/movie#7]
继续#6中的问题
![10957325b4bb31337e54f02d1d46a61](https://user-images.githubusercontent.com/39581263/159907542-17d0bab4-84c1-4291-b8e2-25ff238e70fc.jpg)

**Comment by d1y** [comment]
为什么不用 https://github.com/waifu-project/assets/blob/master/s.json 这里的资源

> ps: 可能是vpn问题吧, 网络加载失败了

**Comment by AlterGu** [comment]
> 

也不行, 挺奇怪的, 安卓12, 安卓9都这样

**Comment by d1y** [comment]
已处理: https://github.com/waifu-project/movie/pull/13
